export const species = [
  {
    name: '大蓝闪蝶', latin: 'Morpho menelaus', color: '#76cbe5',
    representative: '雄性 · huebneri 亚种 · 巴西 Pará',
    specimenDorsal: 'https://commons.wikimedia.org/wiki/File:Morpho_menelaus_huebneri_MHNT_Male_Dos.jpg',
    specimenVentral: 'https://commons.wikimedia.org/wiki/File:Morpho_menelaus_huebneri_MHNT_Male_ventre.jpg',
    bodyReference: 'https://www.inaturalist.org/observations/339774357',
    bodyReferenceLabel: '闪蝶侧面记录（性别、亚种未确认）',
    variation: '选取图卢兹自然史博物馆发布的 huebneri 雄性、Pará 配对照片，不混用其他亚种或雌性翅纹。页面未提供此个体馆藏号及采集日期；亚种名沿用照片记录，不在此解决分类修订。不能将其眼斑大小、蓝色范围视为全物种固定特征。',
    dorsalObservation: '背面：宽阔蓝色翅面、深色端缘与前翅端部浅斑；脉纹取自该雄性标本，不另画装饰线。',
    ventralObservation: '腹面：褐色底与波状带纹；这组照片每片前翅可见 3 枚、后翅 4 枚大小不等的眼斑，不是所有闪蝶的固定公式。',
    sideObservation: '侧面：观察分节身体、棒状触角和胸腹侧的足。前足退化；足姿与身体厚度为待三维资料校准的近似。',
    wikipedia: 'https://en.wikipedia.org/wiki/Morpho_menelaus',
    reference: 'https://doi.org/10.1098/rspb.1999.0794', referenceLabel: '鳞片光学研究',
    habitat: '南美洲热带森林', size: '大型蝴蝶', palette: '蓝色结构色', habit: '日间活动 · 林间飞行',
    title: '一抹蓝，是光的建筑',
    text: '翅面鳞片具有精细的微纳结构，能选择性地反射光线，产生耀眼的<strong>结构色</strong>。这种蓝并不只是蓝色色素的结果；观察角度改变，亮度与色调也随之变化。',
    title2: '同一标本，两种表面',
    text2: '本图谱的蓝色背面和褐色眼斑腹面分别来自具名标本照片，翻转即可比较。前后翅眼斑大小和位置不同；保留原照片的色彩与主要脉纹，不以同一张纹理代替两面。结构色随角度的真实反射谱尚未模拟。'
  },
  {
    name: '帝王蝶', latin: 'Danaus plexippus', color: '#e8a05d',
    representative: '雄性 · plexippus 指名亚种 · 魁北克',
    specimenDorsal: 'https://commons.wikimedia.org/wiki/File:Danaus_plexippus_MHNT_dos.jpg',
    specimenVentral: 'https://commons.wikimedia.org/wiki/File:Danaus_plexippus_MHNT_ventre.jpg',
    bodyReference: 'https://commons.wikimedia.org/wiki/File:Closeup_of_a_monarch_head,_newly_emerged_from_the_chrysalis_(29707955337).jpg',
    bodyReferenceLabel: '帝王蝶头胸微距（非同一个体）',
    variation: '依据 MHNT 配对照片，馆藏字段原文为 MNHT.CUT.2011.0.171：加拿大魁北克 Lac Valmont，雄性 D. p. plexippus。未核实采集日期；照片拍摄时间不能当采集时间。雄性后翅背面的黑色性斑保留；雌性没有这种性斑且黑色脉纹通常更宽，不能以此雄性代表雌性。照片个体的磨损、展翅姿态与照明不是物种常量。',
    dorsalObservation: '背面：橙底黑脉、不规则边缘白斑；两片后翅各有一枚雄性黑色性斑，雌性不具这一特征。',
    ventralObservation: '腹面：后翅较背面浅，前翅端部浅斑更显眼；使用同组腹面照片，不把背面性斑额外复制到腹面。',
    sideObservation: '侧面：触角端部膨大；头、胸、腹分区与腹节可见。两条短前足贴近胸部，四条中后足作步行足。',
    wikipedia: 'https://en.wikipedia.org/wiki/Monarch_butterfly',
    reference: 'https://www.fws.gov/species/monarch-danaus-plexippus', referenceLabel: '美国鱼类及野生动物管理局',
    habitat: '美洲原生 · 多地有分布', size: '中大型蝴蝶', palette: '橙底黑脉 · 白点边缘', habit: '幼虫以乳草类植物为食',
    title: '跨越世代的迁徙',
    text: '<strong>北美部分种群</strong>进行长距离季节迁徙。落基山脉以东的迁徙种群主要前往墨西哥中部越冬，西部种群多在加利福尼亚沿海越冬。并非所有帝王蝶种群都迁徙，路线与越冬地点也有变异。',
    title2: '一场旅程，不止一代生命',
    text2: '秋季的迁徙一代可存活较长时间；向北扩展的过程通常由连续几代共同完成。乳草是幼虫重要的食物来源，成蝶则访问花朵取食花蜜。保护繁殖、迁徙与越冬栖息地，缺一不可。'
  }
];
